### PR TITLE
Automates process described in last two steps of Model subgenerator section in README.

### PR DESCRIPTION
**Pull request by jobobo21**
I use this generator every day and made this slight modification for personal use. I feel it is my responsibility to share my contribution. So if you want to add this then great if not then no worries Il keep it for myself.

### CODE REVIEW

**Comment by gillchristian** [comment]
Thanks for the PR @jobobo21 !!!

Could you change the formatting back to how it was so the diff is only on the real changes you added?

Also it would be great if you could add tests for this new feature.

**Comment by jobobo21** [comment]
Ahh yeah sorry bout the formatting I thought that my editor had got it correct based on your linter file however there must have been some error. However I'll work on adding some tests in model.spec.js

**Comment by jobobo21** [comment]
Do you guys need me to add some comments? Just realized it may look odd from an outsiders perspective.

**Comment by ndelvalle** [comment]
No worries @jobobo21 thank you very much for your contribution. I will fix the bithound issues, test it locally and try to add some tests, then I'll publish a new version.

**Comment by ndelvalle** [comment]
I'm glad you found this library useful @jobobo21  🙂

**Comment by jobobo21** [comment]
Yup no worries your welcome

**Pull request merged**
