### PR TITLE
Model subgenerator

### PR DESCRIPTION
**Pull request by Sin-**
I added a model subgenerator because most of the work was already done and it was itching me ^^
You call `yo api:model` and you can add one or multiple models to the project.
I didn't modify the README.

### CODE REVIEW

**Comment by gillchristian** [comment]
Looks great! No worries about the readme.

If you could add tests that'd be great! Just some simple ones like those we have for the main generator. If you have any questions regarding this just let me know.

**Comment by tomexa** [comment]
Ok, as soon I have the time I'll add the tests.

**Comment by tomexa** [comment]
I added this code to the test file: 
```
describe('Run yeoman sub-generator api:model', () => {

    before(() => {
      helpers.run(path.join(__dirname, '../generators/app'))
      .withPrompts({
        serverName: 'serverName',
        serverDescription: 'serverDescription',
        serverVersion: 'serverVersion',
        authorName: 'authorName',
        authorEmail: 'authorEmail',
        models: ['foo'],
        databaseName: 'databaseName',
        useDocker: false
      })
      .then(() => {
        helpers.run(path.join(__dirname, '../generators/model'))
        .withPrompts({
          models: ['model1', 'model2']
        })
        .toPromise();
      });
    });

    describe('models', () => {
      it('generates a folder for each model', () => {
        assert.file([
          'model/model1',
          'model/model2'
        ]);
      });

      describe('controllers', () => {
        it('generates a controller for each model', () => {
          assert.file([
            'model/model1/model1-controller.js',
            'model/model2/model2-controller.js'
          ]);
        });
      });

      describe('facades', () => {
        it('generates a facade for each model', () => {
          assert.file([
            'model/model1/model1-facade.js',
            'model/model2/model2-facade.js'
          ]);
        });
      });

      describe('routes', () => {
        it('generates a router for each model', () => {
          assert.file([
            'model/model1/model1-router.js',
            'model/model2/model2-router.js'
          ]);
        });
      });

      describe('schemas', () => {
        it('generates a schema for each model', () => {
          assert.file([
            'model/model1/model1-schema.js',
            'model/model2/model2-schema.js'
          ]);
        });
      });
    });
  });
```
But the first test fails.
I'm new to unit tests for yeoman generators so maybe I got it all wrong, I found little to no documentation on this, neither on the yeoman website nor with google...

**Comment by gillchristian** [comment]
I guess `yeoman-assert`'s file assertion does not work for folders. You can omit that test case, since the other tests cover the existence of the folders anyways.

**Comment by tomexa** [comment]
Removed the first test, the second one failed just the same. 
Either I have a path problem, or I missed a step...

**Comment by gillchristian** [comment]
I think my guess was wrong, all the tests are actually failing, but it is configured to bail at the first failure.

I was able to run your tests locally and I get an error about a file is missing `/tmp/1ee33b06/routes.js`. I assume is the one [referenced here](https://github.com/Sin-/generator-api/blob/master/generators/model/index.js#L47). Maybe if you correct the path to that `routes.js` file the tests will pass.

**Comment by tomexa** [comment]
I had this error too before but it was because I was only running
`helpers.run(path.join(__dirname, '../generators/model'))`
without running the base generator.
It seems that the test script create a temporary file architecture and it is deleted after each test.
My subgenerator needs the `routes.js` file created by the base generator, that's why I call it in the nested promise after calling the main generator.
It solved the `routes.js` error but now the asserts keep failing... 
I tried debugging the test script with `node-inspector` but without success =/
Hmmm...

**Comment by gillchristian** [comment]
What errors are you having now?

Maybe we can merge the PR and then fix the tests. I assume you tested manually that it works :upside_down_face:

What do you think @ndelvalle ?

**Comment by ndelvalle** [comment]
thanks @Sin- we will go over the test before pushing a new release.

**Comment by Sin-** [comment]
No problem! Let me know what I did wrong in the unit test when you figure it out 🙂
Thanks!

**Pull request merged**
